feat(font cache):add font cache in service worker
delta/aaveg-21 pull request #50
Opened 2021-04-18 20:57 UTC by Muhesh7

2021-04-18 21:04 UTC, indreshp135 requested changes

2021-04-18 21:04 UTC, indreshp135 commented on client/src/index.css
> +  box-shadow: 0 0 0 100px #563710 inset !important;
This will affect the look of homepage

2021-04-19 05:03 UTC, geforce6t approved these changes

2021-04-19 05:18 UTC, indreshp135 approved these changes

2021-04-19 05:18 UTC, merged